Add lock manager related api
tcdi/pgrx pull request #1140
Opened 2023-05-19 10:23 UTC by usamoi

The project I'm working for needs those APIs for managing pages. Thank you for your appreciated work.

2023-05-20 02:35 UTC, usamoi commented
Sorry. Now it's ready to be merged.

2023-05-23 15:15 UTC, eeeebbbbrrrr requested changes

2023-05-23 15:15 UTC, eeeebbbbrrrr commented on pgrx-pg-sys/src/submodules/panic.rs
> +        if crate::ERROR == self.level as _ {
why is this change part of this PR?

2023-05-23 15:19 UTC, usamoi commented on pgrx-pg-sys/src/submodules/panic.rs
> +        if crate::ERROR == self.level as _ {
Removed now.

2023-05-23 16:49 UTC, merged