Add --configure-flag option for cargo pgrx init
tcdi/pgrx pull request #1154
Opened 2023-05-30 10:07 UTC by ewencp

This allows passing through flags to the `configure` script when building postgres. For example, using
`'--configure-flag=--with-ssl=openssl'` enables openssl support, including contrib extensions like pgcrypto.

2023-05-30 14:43 UTC, ewencp commented
I previously implemented #1065 to include contrib extensions. However, not everything gets included because some require additional configs to be enabled -- pgcrypto is specifically relevant to my use case so I used that as an example. Using this to pass `--with-ssl`, `--with-includes` and `--with-libraries` gets the extension installed so it can be usable. Since it's just passing things along to `configure`, it also works for core postgres functionality that's toggleable at build time.

2023-05-31 14:13 UTC, eeeebbbbrrrr requested changes
If you will, please update the `cargo-pgrx/README.md` with this new flag.  Then I think this will be ready to merge.

2023-05-31 15:42 UTC, ewencp commented
Updated. That section is getting a bit unwieldy for adding docs to, it might need to be broken up into subsections for different use cases at some point to make it more manageable (and perhaps not all flags need to be documented there as long as they are documented clearly enough in the `--help` output).

2023-05-31 17:42 UTC, eeeebbbbrrrr approved these changes

2023-05-31 17:43 UTC, eeeebbbbrrrr commented
Thanks, @ewencp.

It's to have at least something in pgrx where the complaint is "too many docs"!  If we had the resources, I'd kick off a mdbook project for pgrx.

2023-05-31 17:44 UTC, merged